Add a last mile check on destination images
I'm experiencing (twice already) qcow2 corruption (i.e., guest OS boots into
kernel panic).

So, just in case, let's add a last mile check before touching the images!

Worth to mention that SVAuto uses Ansible's stat module already...

diff --git a/ansible/roles/ubuntu-virt/tasks/clone_qcow2.yml b/ansible/roles/ubuntu-virt/tasks/clone_qcow2.yml
--- a/ansible/roles/ubuntu-virt/tasks/clone_qcow2.yml
+++ b/ansible/roles/ubuntu-virt/tasks/clone_qcow2.yml
@@ -25,7 +25,15 @@
 
 
 - name: clone_qcow2 - Clone {{ disk.source }} to {{ disk_destination }} Format QCoW2 ({{ vm.name }})
-  shell: "qemu-img convert -f {{ disk.driver.type }} -O {{ disk.driver.type }} {{ disk.source }} {{ disk_destination }}"
+  shell: |
+    if [ -f "{{ disk_destination }}" ]
+    then
+       echo "WARNING! File {{ disk_destination }} already exists!"
+       echo "ABORTING!"
+       exit 1
+    fi
+    qemu-img convert -f {{ disk.driver.type }} -O {{ disk.driver.type }} {{ disk.source }} {{ disk_destination }}
+    exit
   when: not disk_existance.stat.exists
 
 - name: clone_qcow2 - Set {{ disk_destination }} size to {{ disk.size }}G
diff --git a/ansible/roles/ubuntu-virt/tasks/clone_qcow2c.yml b/ansible/roles/ubuntu-virt/tasks/clone_qcow2c.yml
--- a/ansible/roles/ubuntu-virt/tasks/clone_qcow2c.yml
+++ b/ansible/roles/ubuntu-virt/tasks/clone_qcow2c.yml
@@ -25,13 +25,29 @@
 
 
 - name: clone_qcow2c - Clone with cp {{ disk.source }} to {{ disk_destination }} Format Compressed QCoW2 ({{ vm.name }})
-  shell: "cp {{ disk.source }} {{ disk_destination }}"
+  shell: |
+    if [ -f "{{ disk_destination }}" ]
+    then
+       echo "WARNING! File {{ disk_destination }} already exists!"
+       echo "ABORTING!"
+       exit 1
+    fi
+    cp -n {{ disk.source }} {{ disk_destination }}
+    exit
   when:
   - not disk_existance.stat.exists
   - disk.driver.clone_cp is defined and disk.driver.clone_cp
 
 - name: clone_qcow2c - Clone with qemu-img {{ disk.source }} to {{ disk_destination }} Format Compressed QCoW2 ({{ vm.name }})
-  shell: "qemu-img convert -c -f {{ disk.driver.type }} -O {{ disk.driver.type }} {{ disk.source }} {{ disk_destination }}"
+  shell: |
+    if [ -f "{{ disk_destination }}" ]
+    then
+       echo "WARNING! File {{ disk_destination }} already exists!"
+       echo "ABORTING!"
+       exit 1
+    fi
+    qemu-img convert -c -f {{ disk.driver.type }} -O {{ disk.driver.type }} {{ disk.source }} {{ disk_destination }}
+    exit 0
   when:
   - not disk_existance.stat.exists
   - disk.driver.clone_cp is undefined and not disk.driver.clone_cp
diff --git a/ansible/roles/ubuntu-virt/tasks/empty_qcow2.yml b/ansible/roles/ubuntu-virt/tasks/empty_qcow2.yml
--- a/ansible/roles/ubuntu-virt/tasks/empty_qcow2.yml
+++ b/ansible/roles/ubuntu-virt/tasks/empty_qcow2.yml
@@ -25,7 +25,15 @@
 
 
 - name: empty_qcow2 - Create {{ disk_destination }} format qcow2 ({{ vm.name }})
-  shell: "qemu-img create -f {{ disk.driver.type }} {{ disk_destination }} {{ disk.size }}G"
+  shell: |
+    if [ -f "{{ disk_destination }}" ]
+    then
+       echo "WARNING! File {{ disk_destination }} already exists!"
+       echo "ABORTING!"
+       exit 1
+    fi
+    qemu-img create -f {{ disk.driver.type }} {{ disk_destination }} {{ disk.size }}G
+    exit 0
   when: not disk_existance.stat.exists
 
 - name: empty_qcow2 - Set file permissions for {{ disk_destination }} ({{ vm.name }})
diff --git a/ansible/roles/ubuntu-virt/tasks/empty_qcow2c.yml b/ansible/roles/ubuntu-virt/tasks/empty_qcow2c.yml
--- a/ansible/roles/ubuntu-virt/tasks/empty_qcow2c.yml
+++ b/ansible/roles/ubuntu-virt/tasks/empty_qcow2c.yml
@@ -30,8 +30,15 @@
 
 - name: empty_qcow2c - Create {{ disk_destination }} Compressed QCoW2 ({{ vm.name }})
   shell: |
+    if [ -f "{{ disk_destination }}" ]
+    then
+       echo "WARNING! File {{ disk_destination }} already exists!"
+       echo "ABORTING!"
+       exit 1
+    fi
     qemu-img create -f "{{ disk.driver.type }}" "{{ disk_tmp_destination }}" "{{ disk.size }}G"
     qemu-img convert -c -f "{{ disk.driver.type }}" -O "{{ disk.driver.type }}" "{{ disk_tmp_destination }}" "{{ disk_destination }}"
+    exit 0
   when: not disk_existance.stat.exists
 
 - name: empty_qcow2c - Remove tmp image
